### ISSUE TITLE
Integrate with WooCommerce Core Usage Tracking

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/woocommerce-google-analytics-integration#175]
As of WooCommerce 2.3, WooCommerce provides the ability for Merchants to enable usage tracking from within their WordPress admin area. This sends Woo basic data about the size of the store, how WooCommerce is installed, and how it’s being used.

By choosing to share your data, Merchants help us make WooCommerce better for everyone. By understanding how you’re using WooCommerce, we can create more helpful features, write better documentation, and make WooCommerce a more useful platform.

More information here: https://woocommerce.com/usage-tracking/

---

Tracker Data

* TBC

Event tracking

* TBC

---

Acceptance Criteria

* [x] Tracker data capture
* [ ] Tracks events fired
* [ ] Tracking enabled only if enabled by Merchant

**Comment by layoutd** [comment]
WC Tracker snapshot data is already implemented using the core `woocommerce_tracker_data` hook:
https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/8c6c6a159b30e7d5eeaf65d8bdc15730b52e0b85/includes/class-wc-google-analytics.php#L242-L253
